# Generated by Django 4.1.7 on 2023-02-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_Verified",
            new_name="is_verified",
        ),
    ]
